name: Scrape and commit

on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # scrape fireside for latest shows
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install deps and scrape fireside
        run: |
          pip install -U -r requirements.txt
          python3 scrape.py

      # automatically adds changed files in docs directory to git
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatically scraped and committed via a GitHub Action."